name: Run tests and report coverage

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'main'

jobs:
  run-tests-and-report-coverage:
    name: Run tests and reports coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn

      - name: Test
        run: yarn test:ci:coverage

      - name: Report code coverage
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/*.lcov:lcov
